name: Generate Contributor Pie Chart

on:
  workflow_call:
    inputs:
      chart-size:
        required: false
        type: string
        default: '6,6'
      palette:
        required: false
        type: string
        default: '#EBE8DB, #D76C82, #B03052, #3D0301'
      repo-url:
        required: true
        type: string


jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caller Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Generator Repo
        uses: actions/checkout@v4
        with:
          repository: redfyel/contrib-pie-generator
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          path: generator

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib requests

      - name: Generate Chart
        run: |
          if [ "${{ inputs.palette }}" != "" ]; then
            python generator/generate.py "${{ inputs.chart-size }}" "${{ inputs.palette }}" "${{ inputs.repo-url }}"
          else
            python generator/generate.py "${{ inputs.chart-size }}" "" "${{ inputs.repo-url }}"
          fi

      - name: Commit Chart and Update README
        run: |
          # Append image reference to README.md if not already present
          if ! grep -q "!\[Contributor Pie Chart\](contributor-pie.png)" README.md; then
              echo -e "\n![Contributor Pie Chart](contributor-pie.png)" >> README.md
          fi
          
          # Set Git user and commit the changes (chart + README update)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contributor-pie.png README.md
          
          # Commit and push changes, if any
          git commit -m "📊 Auto-update contributor pie chart and update README" || echo "No changes"
          
          # Push changes to the repository
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
