name: Generate Contributor Pie Chart

on:
  workflow_call:
    inputs:
      chart-size:
        required: false
        type: string
        default: '6,6'

jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      # Checkout the caller repository if needed
      - name: Checkout Caller Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Explicitly checkout the generator repo
      - name: Checkout Generator Repo
        uses: actions/checkout@v4
        with:
          repository: redfyel/contrib-pie-generator
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure proper access
          fetch-depth: 0
          path: generator

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib

      # Run the generate.py script from the checked-out generator repo directory
      - name: Generate Chart
        run: python generator/generate.py ${{ inputs.chart-size }}

      - name: Commit Chart
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add contributor-pie.png
          git commit -m "📊 Auto-update contributor pie chart" || echo "No changes"
          git push
